
---
- name: HA Proxy setup
  hosts:
    - localhost
  remote_user: root

  tasks:
    - name: Add haproxy packages
      apt:
        name: haproxy
        state: present

    - name: Cfg haproxy - tcp mode
      lineinfile:
        path: /etc/haproxy/haproxy.cfg
        backrefs: yes
        backup: no
        regexp: '^(\s+mode\s+)http$'
        line: '\1tcp'
    - name: Cfg haproxy - tcplog
      lineinfile:
        path: /etc/haproxy/haproxy.cfg
        backrefs: yes
        backup: no
        regexp: '^(\s+option\s+)httplog$'
        line: '\1tcplog'
    - name: Cfg haproxy - redispatch
      lineinfile:
        path: /etc/haproxy/haproxy.cfg
        backrefs: no
        backup: no
        insertafter: '^\s+option\s+dontlognull$'
        regexp: '^\s+option\s+redispatch$'
        line: '        option  redispatch'
    - name: Cfg haproxy - tcpka
      lineinfile:
        path: /etc/haproxy/haproxy.cfg
        backrefs: no
        backup: no
        insertafter: '^\s+option\s+redispatch$'
        regexp: '^\s+option\s+tcpka$'
        line: '        option  tcpka'
    - name: Cfg haproxy - retries
      lineinfile:
        path: /etc/haproxy/haproxy.cfg
        backrefs: no
        backup: no
        insertafter: '^\s+option\s+tcpka$'
        regexp: '^\s+retries\s+2$'
        line: '        retries 2'