
---
- name: HA Proxy setup
  hosts:
    - localhost
  remote_user: root

  tasks:
    - name: Add haproxy packages
      apt:
        name: haproxy
        state: present

    - name: Cfg haproxy - tcp mode
      lineinfile:
        path: /etc/haproxy/haproxy.cfg
        backrefs: yes
        backup: no
        regexp: '^(\s+mode\s+)http$'
        line: '\1tcp'