---
- name: K3s prerequisite - legacy iptables
  hosts:
    - controlplanes
    - workers
  tasks:
    - name: Flush iptables
      command: iptables -f
    - name: Set iptables legacy
      command: update-alternatives --set iptables /usr/sbin/iptables-legacy
    - name: Set ip6tables legacy
      command: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy