---
- name: K3s prerequisite - legacy iptables
  hosts:
    - controlplanes
    - workers
  tasks:

    - name: Flush iptables
      command: iptables -F
    - name: Set iptables legacy
      command: update-alternatives --set iptables /usr/sbin/iptables-legacy
    - name: Set ip6tables legacy
      command: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

    - name: Enable cgroups
      ansible.builting.lineinfile:
        state: present
        path: /boot/cmdline.txt
        insertafter: EOF
        line: " cgroup_memory=1 cgroup_enable=memory"