---
- name: K3s prerequisite - legacy iptables
  hosts:
    - controlplanes
    - workers
  remote_user: root

  tasks:
    - name: Flush iptables
      command: iptables -F
    - name: Set iptables legacy
      command: update-alternatives --set iptables /usr/sbin/iptables-legacy
    - name: Set ip6tables legacy
      command: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

- name: K3s prerequisites - enable cgroups
  hosts:
    - controlplanes
    - workers
  remote_user: root

  tasks:
    - name: Enable cgroups
      lineinfile:
        state: present
        path: /boot/cmdline.txt
        backrefs: yes
        regexp: "(rootwait)$"    
        line: '\1 cgroup_memory=1 cgroup_enable=memory'